name: Migrate

on:
  workflow_call:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run migrations
        uses: ./.github/actions/migrate
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          deploy-path: ${{ secrets.DEPLOY_PATH }}
