name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/Lint.yml

  migrate:
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/migrate.yml
    secrets: inherit

  deploy:
    needs: migrate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
