name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/Lint.yml

  payment-health:
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check payment-service
        uses: ./.github/actions/payment-health
        with:
          host: ${{ vars.PAY_SERVICE_HOST }}

  migrate:
    needs: payment-health
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/migrate.yml
    secrets: inherit

  deploy:
    needs: migrate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
